// utils/plans.js
export const PLANS = [
  {
    key: 'static',
    badge: 'One Time',
    subtitle: '',
    title: 'Static Website',
    priceUsd: 180,
    saleUsd: 110,
    highlight: false,
    features: [
      ['2 Pages', true],
      ['SSL(full Website Security)', true],
      ['Domain Connection Setup', true],
      ['Mobile Responsive', true],
      ['Contact Form', true],
      ['Support(1 month free)', true],
      ['Customized Updates', true],
      ['Fully Tested', true],
      ['Social Media Integration', true],
      ['Complete SEO Friendly', false],
      ['Content', false],
      ['Complete Admin Panel', false],
      ['Addon Modules', false],
      ['Fully Authenticated', false],
      ['Graphics', false],
    ],
  },
  {
    key: 'dynamic',
    badge: 'One Time',
    subtitle: '',
    title: 'Dynamic Website',
    priceUsd: 389,
    saleUsd: 219,
    highlight: false,
    features: [
      ['2 Pages', true],
      ['SSL(full Website Security)', true],
      ['Domain Connection Setup', true],
      ['Mobile Responsive', true],
      ['Contact Form', true],
      ['Support(1 month free)', true],
      ['Customized Updates', true],
      ['Fully Tested', true],
      ['Social Media Integration', true],
      ['Complete SEO Friendly', false],
      ['Content With', false],
      ['Complete Admin Panel', false],
      ['Addon Modules', false],
      ['Fully Authenticated', false],
      ['Graphics', false],
    ],
  },
  {
    key: 'seo',
    badge: 'One Time',
    subtitle: '',
    title: 'Dynamic with SEO',
    priceUsd: 550,
    saleUsd: 320,
    highlight: false,
    features: [
      ['2 Pages', true],
      ['SSL(full Website Security)', true],
      ['Domain Connection Setup', true],
      ['Mobile Responsive', true],
      ['Contact Form', true],
      ['Support(3 months free)', true],
      ['Customized Updates', true],
      ['Fully Tested', true],
      ['Social Media Integration', true],
      ['Complete SEO Friendly', true],
      ['Content With', true],
      ['Complete Admin Panel', false],
      ['Addon Modules', false],
      ['Fully Authenticated', false],
      ['Graphics', false],
    ],
  },
  {
    key: 'complete',
    badge: 'One Time',
    subtitle: 'Graphics & Dynamic',
    title: 'Dynamic with Admin',
    priceUsd: 899,
    saleUsd: 500,
    highlight: false,
    features: [
      ['2 Pages', true],
      ['SSL(full Website Security)', true],
      ['Domain Connection Setup', true],
      ['Mobile Responsive', true],
      ['Contact Form', true],
      ['Support(6 months free)', true],
      ['Customized Updates', true],
      ['Fully Tested', true],
      ['Social Media Integration', true],
      ['Complete SEO Friendly', true],
      ['Content With', true],
      ['Complete Admin Panel', true],
      ['Addon Modules', true],
      ['Fully Authenticated', true],
      ['Graphics', true],
    ],
  },
];


export default PLANS; 

