// export const PLANS = [
//   {
//     key: "static",
//     title: "Static Website",
//     price: "₹15,999",
//     sale: "₹11,999",
//     badge: "One Time",
//     features: [
//       ["5 Pages", true],
//       ["Mobile Responsive", true],
//       ["Contact Form", true],
//       ["Online Support", true],
//       ["Customized Updates", true],
//       ["Fully Tested", true],
//       ["Social Media Integration", false],
//       ["Content", false],
//       ["Complete Admin Panel", false],
//       ["Complete SEO Friendly", false],
//       ["Addon Modules", false],
//       ["Graphics", false]
//     ]
//   },
//   {
//     key: "dynamic",
//     title: "Dynamic Website",
//     price: "₹24,999",
//     sale: "₹18,499",
//     badge: "One Time",
//     features: [
//       ["5 Pages", true],
//       ["Mobile Responsive", true],
//       ["Contact Form", true],
//       ["Online Support", true],
//       ["Customized Updates", true],
//       ["Fully Tested", true],
//       ["Social Media Integration", true],
//       ["Content With", false],
//       ["Complete Admin Panel", true],
//       ["Complete SEO Friendly", true],
//       ["Addon Modules", false],
//       ["Graphics", false]
//     ]
//   },
//   {
//     key: "dynamic-seo",
//     title: "Dynamic with SEO",
//     price: "₹40,999",
//     sale: "₹31,499",
//     badge: "One Time",
//     features: [
//       ["5 Pages", true],
//       ["Mobile Responsive", true],
//       ["Contact Form", true],
//       ["Online Support", true],
//       ["Customized Updates", true],
//       ["Fully Tested", true],
//       ["Content With", true],
//       ["Social Media Integration", true],
//       ["Complete Admin Panel", true],
//       ["Complete SEO Friendly", true],
//       ["Addon Modules", true],
//       ["Graphics", true]
//     ]
//   },
//   {
//     key: "complete",
//     title: "Complete Package",
//     subtitle: "Graphics & Dynamic",
//     price: "₹65,999",
//     sale: "₹49,999",
//     badge: "One Time",
//     highlight: true,
//     features: [
//       ["5 Pages", true],
//       ["Mobile Responsive", true],
//       ["Contact Form", true],
//       ["Online Support", true],
//       ["Customized Updates", true],
//       ["Fully Tested", true],
//       ["Content With", true],
//       ["Social Media Integration", true],
//       ["Complete Admin Panel", true],
//       ["Complete SEO Friendly", true],
//       ["Addon Modules", true],
//       ["Graphics", true]
//     ]
//   }
// ];


//////

// utils/plans.js
export const PLANS = [
  {
    key: 'static',
    badge: 'One Time',
    subtitle: '',
    title: 'Static Website',
    priceUsd: 499,
    saleUsd: 399,
    highlight: false,
    features: [
      ['5 Pages', true],
      ['Mobile Responsive', true],
      ['Contact Form', true],
      ['Online Support', true],
      ['Customized Updates', true],
      ['Fully Tested', true],
      ['Social Media Integration', false],
      ['Content', false],
      ['Complete Admin Panel', false],
      ['Complete SEO Friendly', false],
      ['Addon Modules', false],
      ['Graphics', false],
    ],
  },
  {
    key: 'dynamic',
    badge: 'One Time',
    subtitle: '',
    title: 'Dynamic Website',
    priceUsd: 799,
    saleUsd: 649,
    highlight: false,
    features: [
      ['5 Pages', true],
      ['Mobile Responsive', true],
      ['Contact Form', true],
      ['Online Support', true],
      ['Customized Updates', true],
      ['Fully Tested', true],
      ['Social Media Integration', true],
      ['Content With', false],
      ['Complete Admin Panel', true],
      ['Complete SEO Friendly', true],
      ['Addon Modules', false],
      ['Graphics', false],
    ],
  },
  {
    key: 'seo',
    badge: 'One Time',
    subtitle: '',
    title: 'Dynamic with SEO',
    priceUsd: 1099,
    saleUsd: 899,
    highlight: false,
    features: [
      ['5 Pages', true],
      ['Mobile Responsive', true],
      ['Contact Form', true],
      ['Online Support', true],
      ['Customized Updates', true],
      ['Fully Tested', true],
      ['Content With', true],
      ['Social Media Integration', true],
      ['Complete Admin Panel', true],
      ['Complete SEO Friendly', true],
      ['Addon Modules', true],
      ['Graphics', true],
    ],
  },
  {
    key: 'complete',
    badge: 'One Time',
    subtitle: 'Graphics & Dynamic',
    title: 'Complete Package',
    priceUsd: 1499,
    saleUsd: 1199,
    highlight: true,
    features: [
      ['5 Pages', true],
      ['Mobile Responsive', true],
      ['Contact Form', true],
      ['Online Support', true],
      ['Customized Updates', true],
      ['Fully Tested', true],
      ['Content With', true],
      ['Social Media Integration', true],
      ['Complete Admin Panel', true],
      ['Complete SEO Friendly', true],
      ['Addon Modules', true],
      ['Graphics', true],
    ],
  },
];
